### PR TITLE
Add vcomp macro.

### PR DESCRIPTION
**Pull request by Ismael-VC**
`@vcomp` (_vector comprehension_) based on Python's list comprehensions
with a conditional clause to filter elements in a succinct way.

### CODE REVIEW

**Comment by Ismael-VC** [comment]
I'll wait for tests to pass so I can squash commits, I'm not at home with my laptop, so I had to use :octocat:  web interface for the moment which doesn't allow for this.

**Comment by ChrisRackauckas** [comment]
Tests are failing for v0.5. At this point, I value v0.5 compatibility over v0.4. I don't think there's a reason to promise backwards compatibility at this point. Please update to at least pass tests on v0.5.

**Comment by ChrisRackauckas** [comment]
Don't worry about the v0.4 tests, they will fail because it's testing that the `multireshape` function is actually using a view. But the v0.5 tests should pass.

**Comment by Ismael-VC** [comment]
@ChrisRackauckas tests are passing, I just rechecked everything, it works on both versions of Julia, but currently there is also another error in the 0.4 unrelated to this PR:
- https://travis-ci.org/ChrisRackauckas/VectorizedRoutines.jl/jobs/147514257#L201

If the target is going to be only 0.5 maybe it would be a good idea tu raise the version needed in REQUIRE and disable 0.4 tests, also since we don't need any binary dependency that is specific of the platform Win vs Linux for example, I think there is no need to be using both AppVeyour and TravisCI, usually Travis is a lot faster, but this are only some suggestions of course! :D

**Pull request merged**
