### PR TITLE
Sub instead of view on 0.4

### LINKED ISSUE #3: UndefVarError: view not defined
I was rebasing and squashing #2 but test fails on `Julia.multireshape` on v0.4:
- https://ci.appveyor.com/project/ChrisRackauckas/vectorizedroutines-jl/build/1.0.18/job/04uvh1mlggw07wox#L57

```
C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"VectorizedRoutines\")"
INFO: Testing VectorizedRoutines
ERROR: LoadError: UndefVarError: view not defined
 in multireshape at C:\Users\appveyor\.julia\v0.4\VectorizedRoutines\src\julia.jl:18
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in process_options at client.jl:280
 in _start at client.jl:377
while loading C:\Users\appveyor\.julia\v0.4\VectorizedRoutines\test\runtests.jl, in expression starting on line 12
=========================[ ERROR: VectorizedRoutines ]==========================
failed process: Process(`'C:\projects\julia\bin\julia' --check-bounds=yes --code-coverage=none --color=no 'C:\Users\appveyor\.julia\v0.4\VectorizedRoutines\test\runtests.jl'`, ProcessExited(1)) [1]
================================================================================
ERROR: VectorizedRoutines had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at client.jl:257
 in _start at client.jl:377
Command exited with code 1
```

### PR DESCRIPTION
**Pull request by Ismael-VC**
~~Fixes~~ #3

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Now I get this error: 

``` julia
ERROR: LoadError: test failed: 26 == 42
 in expression: (Xs[2])[4,5] == 42
```

**Comment by ChrisRackauckas** [comment]
I don't see this as too necessary. It's not like anyone has really adopted it yet. Since the package is so new, when v0.5 comes out (very soon), I'll be keeping the tests just for release/nightly. I don't see a reason to put too much work into getting everything v0.4 compatible (still, most of the functions will work). But if you think of a quick way to fix this and the tests pass, I'll take it.

**Comment by ChrisRackauckas** [comment]
Merged @ViktorQvarfordt's

**Comment by Ismael-VC** [comment]
I agree, v0.5 should be the target, thanks!

**Pull request closed without merging**
