### PR TITLE
Improve multireshape

### PR DESCRIPTION
**Pull request by ViktorQvarfordt**
Thanks for including my function, here is a slightly improved version with better documentation.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Would you happen to know how to get it to work on v0.4? @Ismael-VC gave it a go but it doesn't seem to evaluate to the right value. You can see it here: https://github.com/ChrisRackauckas/VectorizedRoutines.jl/pull/4/commits/7661381e3227cfd83606a6dd019cea05b2ae1710

It's okay if you can't get it working in v0.4 since backwards compatibility isn't really necessary for this.

**Comment by ViktorQvarfordt** [comment]
The issue with Julia 0.4 is that replacing `view` with `sub` followed by `reshape` causes copying. This is simply how `sub/reshape` works in 0.4 vs. `view/reshape` in 0.5, as illustrated below.

### Example Julia 0.4

``` julia
x = [1,2,3,4]
y = sub(x, 1:4)
# So far the elements of the arrays reference the same data:
y[1] = 100
println(x) # [100,2,3,4]
# But not when reshaped:
z = reshape(y, 2, 2)
z[2,1] = 200
println(x) # [100,2,3,4]
```

### Example Julia 0.5

``` julia
x = [1,2,3,4]
y = view(x, 1:4)
# The arrays reference the same data, also after reshape:
z = reshape(view(x, 1:4), 2, 2)
z[2,1] = 200
println(x) # [1,200,3,4]
```

I realize that one does not always need the non-copying behavior, although it is desired. Therefore, my latest commit reverts to using `sub` rather than `view` for 0.4, and also gives different docstrings for the two cases (depending on Julia version).

See the difference in Julia 0.4 and 0.5 by running

``` julia
x = zeros(26)
y = multireshape(x, (2,3), (4,5))
# The arrays reference the same data, also after reshape:
y[1][1,1] = 1
println(x[1]) # 0 in 0.4 and 1 in 0.5
x[2] = 2
println(y[1][2,1]) # 0 in 0.4 and 2 in 0.5
```

Note that `VERSION > v"0.4+" || (view = sub)` does not work, I got errors overwriting view, not sure why really. I wrapped the code in a proper if statement instead.

Note also that the documentation is messy, perhaps this should be moved out to a separate file, like https://github.com/JuliaLang/julia/blob/master/base/docs/helpdb/Base.jl

**Comment by ViktorQvarfordt** [comment]
Lol, the reason the CI is failing is that Travis CI is trying to use my example in the 0.5-version-docstring as a test also on Julia 0.4. This is probably because the docstring-example-test thingy does not look at the if-statements. 

AFAIK the fault is not mine, I followed the docs http://docs.julialang.org/en/release-0.4/manual/documentation/#advanced-usage. Someone should complain on Travis CI.

**Comment by ChrisRackauckas** [comment]
Just change it to 1 docstring with "Use Julia 0.5 to avoid copying, i.e. the result of multireshape references the same data." at the bottom.

**Comment by ViktorQvarfordt** [comment]
Yeah, that's a fair compromise.

**Pull request merged**
